import { initList } from './list';
import { initDetail } from './detail/index';
import { gotoTab, initFilters } from './filters';
import { draw } from './graph/draw';
import { buildGenealogy, initLayout } from './graph/layout';
import { initSvg, makeDefs } from './graph/svg';
import { initViewport } from './graph/viewport';
import { restoreLocation, saveLocation } from './location';
import { initNavigation } from './navigation';
import { initSurvey } from './survey/index';
import './style.css';
initSvg();
initFilters();
initList();
initNavigation();
initDetail();
initViewport();
initSurvey();
initLayout();
buildGenealogy();
makeDefs();
restoreLocation();
document.querySelectorAll<HTMLElement>('#tabs button').forEach(b => b.addEventListener('click', () => gotoTab(b.dataset.tab)));
window.addEventListener('hashchange', restoreLocation);
['click', 'input', 'change', 'keydown'].forEach(event => document.addEventListener(event, () => setTimeout(saveLocation, 0), true));
window.addEventListener('resize', draw);
